<?php

namespace AppBundle\Repository;

/**
 * WhatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhatRepository extends \Doctrine\ORM\EntityRepository
{
}
